---
- name: Change password on initial login
  delegate_to: 127.0.0.1
  expect:
    command: ssh {{ ssh_args }} {{ password_init_default_user }}@{{ password_init_host }}
    timeout: 10
    responses:
      "(?i)@.*password": "{{ password_init_default_user_password }}"
      "(?i)Current Password": "{{ password_init_default_user_password }}"
      "(?i)New password": "{{ tmp_password }}"
      "(?i)Retypr new password": "{{ tmp_password }}"
  register: change_password_result

- name: change ssh password
  set_fact:
    ansible_ssh_pass: "{{ tmp_password }}"

- name: reset connection
  meta: reset_connection
